let pageList = [
  {
    "id": 0,
    "name": "中焯信息",
    "code": "0",
    "parentId": null,
    "path": ",0,",
    "manager": "lsq002",
    "orderNo": 0,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:15:03",
    "updateTime": null,
    "userList": [],
    "userNums": 0,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "李烁权"
  },
  {
    "id": 99,
    "name": "管理层",
    "code": "001",
    "parentId": 0,
    "path": ",0,99,",
    "manager": "lsq002",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:53:18",
    "updateTime": null,
    "userList": [
      {
        "id": 516,
        "userId": "zlg001",
        "userName": "周林根",
        "postName": "董事长",
        "duty": null,
        "sex": "1",
        "userIdInt": 1,
        "deptId": 99,
        "groupId": 99
      },
      {
        "id": 34,
        "userId": "lsq002",
        "userName": "李烁权",
        "postName": "总经理",
        "duty": "",
        "sex": "1",
        "userIdInt": 2,
        "deptId": 99,
        "groupId": 99
      },
      {
        "id": 68,
        "userId": "ydl014",
        "userName": "杨德良",
        "postName": "副总经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 14,
        "deptId": 99,
        "groupId": 99
      },
      {
        "id": 92,
        "userId": "xm799",
        "userName": "徐明",
        "postName": "技术总监",
        "duty": "负责公司技术管理",
        "sex": "1",
        "userIdInt": 799,
        "deptId": 99,
        "groupId": 99
      },
      {
        "id": 71,
        "userId": "lgq817",
        "userName": "柳刚强",
        "postName": "副总经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 817,
        "deptId": 99,
        "groupId": 99
      }
    ],
    "userNums": 5,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "李烁权"
  },
  {
    "id": 30,
    "name": "财务部",
    "code": "002",
    "parentId": 0,
    "path": ",0,30,",
    "manager": "zj497",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 204,
        "userId": "qzq192",
        "userName": "邱志强",
        "postName": "出纳",
        "duty": null,
        "sex": "1",
        "userIdInt": 192,
        "deptId": 30,
        "groupId": 30
      },
      {
        "id": 205,
        "userId": "zj497",
        "userName": "张健",
        "postName": "财务经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 497,
        "deptId": 30,
        "groupId": 30
      }
    ],
    "userNums": 2,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "张健"
  },
  {
    "id": 15,
    "name": "产品研发中心",
    "code": "003",
    "parentId": 0,
    "path": ",0,15,",
    "manager": "ydl014",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [],
    "userNums": 0,
    "deputyGeneral": "ydl014",
    "deputyGeneralName": "杨德良",
    "managerName": "杨德良"
  },
  {
    "id": 18,
    "name": "技术研发组",
    "code": "003001",
    "parentId": 15,
    "path": ",0,15,18,",
    "manager": "ydl014",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 72,
        "userId": "yjp034",
        "userName": "殷金鹏",
        "postName": "研发主管",
        "duty": null,
        "sex": "1",
        "userIdInt": 34,
        "deptId": 15,
        "groupId": 18
      },
      {
        "id": 86,
        "userId": "cj083",
        "userName": "陈俊",
        "postName": "产品总监",
        "duty": null,
        "sex": "1",
        "userIdInt": 83,
        "deptId": 15,
        "groupId": 18
      },
      {
        "id": 87,
        "userId": "wsy158",
        "userName": "汪深义",
        "postName": "UI设计",
        "duty": null,
        "sex": "1",
        "userIdInt": 158,
        "deptId": 15,
        "groupId": 18
      },
      {
        "id": 73,
        "userId": "xtq291",
        "userName": "许太庆",
        "postName": "研发主管",
        "duty": null,
        "sex": "1",
        "userIdInt": 291,
        "deptId": 15,
        "groupId": 18
      },
      {
        "id": 799,
        "userId": "wdz1408",
        "userName": "王得志",
        "postName": "部门副经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1408,
        "deptId": 15,
        "groupId": 18
      }
    ],
    "userNums": 5,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "杨德良"
  },
  {
    "id": 129,
    "name": "产品组",
    "code": "003002",
    "parentId": 15,
    "path": ",0,15,129,",
    "manager": "cj083",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:48:29",
    "updateTime": null,
    "userList": [
      {
        "id": 35,
        "userId": "zjj294",
        "userName": "赵俊杰",
        "postName": "售前支持",
        "duty": null,
        "sex": "1",
        "userIdInt": 294,
        "deptId": 15,
        "groupId": 129
      },
      {
        "id": 604,
        "userId": "cjn1241",
        "userName": "陈骏南",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1241,
        "deptId": 15,
        "groupId": 129
      },
      {
        "id": 656,
        "userId": "syx1291",
        "userName": "尚亚星",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1291,
        "deptId": 15,
        "groupId": 129
      },
      {
        "id": 727,
        "userId": "gk1353",
        "userName": "高康",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1353,
        "deptId": 15,
        "groupId": 129
      },
      {
        "id": 787,
        "userId": "hrx1396",
        "userName": "胡瑞续",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1396,
        "deptId": 15,
        "groupId": 129
      },
      {
        "id": 791,
        "userId": "xh1400",
        "userName": "薛行",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1400,
        "deptId": 15,
        "groupId": 129
      },
      {
        "id": 796,
        "userId": "wyw1405",
        "userName": "王永旺",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1405,
        "deptId": 15,
        "groupId": 129
      },
      {
        "id": 897,
        "userId": "lf1506",
        "userName": "罗非",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1506,
        "deptId": 15,
        "groupId": 129
      },
      {
        "id": 969,
        "userId": "cbq1572",
        "userName": "楚秉奇",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1572,
        "deptId": 15,
        "groupId": 129
      }
    ],
    "userNums": 9,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "陈俊"
  },
  {
    "id": 101,
    "name": "UI组",
    "code": "003003",
    "parentId": 15,
    "path": ",0,15,101,",
    "manager": "wsy158",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2019-02-18 06:52:26",
    "updateTime": null,
    "userList": [
      {
        "id": 218,
        "userId": "jxj978",
        "userName": "金霞娇",
        "postName": "UI设计",
        "duty": null,
        "sex": "2",
        "userIdInt": 978,
        "deptId": 15,
        "groupId": 101
      },
      {
        "id": 267,
        "userId": "dzh1095",
        "userName": "邓泽红",
        "postName": "UI设计",
        "duty": null,
        "sex": "2",
        "userIdInt": 1095,
        "deptId": 15,
        "groupId": 101
      },
      {
        "id": 742,
        "userId": "lxr1369",
        "userName": "廖萱茹",
        "postName": "UI设计",
        "duty": null,
        "sex": "2",
        "userIdInt": 1369,
        "deptId": 15,
        "groupId": 101
      },
      {
        "id": 859,
        "userId": "dxl1469",
        "userName": "代晓露",
        "postName": "UI设计",
        "duty": null,
        "sex": "2",
        "userIdInt": 1469,
        "deptId": 15,
        "groupId": 101
      },
      {
        "id": 860,
        "userId": "szk1470",
        "userName": "沈志康",
        "postName": "UI设计",
        "duty": null,
        "sex": "1",
        "userIdInt": 1470,
        "deptId": 15,
        "groupId": 101
      },
      {
        "id": 883,
        "userId": "fjh1493",
        "userName": "方杰灏",
        "postName": "UI设计",
        "duty": null,
        "sex": "1",
        "userIdInt": 1493,
        "deptId": 15,
        "groupId": 101
      }
    ],
    "userNums": 6,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "汪深义"
  },
  {
    "id": 16,
    "name": "行情交易业务组",
    "code": "003005",
    "parentId": 15,
    "path": ",0,15,16,",
    "manager": "xtq291",
    "orderNo": 4,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [],
    "userNums": 0,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "许太庆"
  },
  {
    "id": 144,
    "name": "交易组",
    "code": "003005001",
    "parentId": 16,
    "path": ",0,15,16,144,",
    "manager": "xtq291",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:54:58",
    "updateTime": null,
    "userList": [
      {
        "id": 657,
        "userId": "lxw1294",
        "userName": "李新武",
        "postName": "Delphi开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1294,
        "deptId": 15,
        "groupId": 144
      },
      {
        "id": 729,
        "userId": "wjt1355",
        "userName": "王金涛",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1355,
        "deptId": 15,
        "groupId": 144
      },
      {
        "id": 736,
        "userId": "zjj1362",
        "userName": "张晶锦",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1362,
        "deptId": 15,
        "groupId": 144
      }
    ],
    "userNums": 3,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "许太庆"
  },
  {
    "id": 139,
    "name": "接口组",
    "code": "003005002",
    "parentId": 16,
    "path": ",0,15,16,139,",
    "manager": "yf909",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:53:37",
    "updateTime": null,
    "userList": [
      {
        "id": 126,
        "userId": "yf909",
        "userName": "姚锋",
        "postName": "接口开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 909,
        "deptId": 15,
        "groupId": 139
      },
      {
        "id": 655,
        "userId": "djt1290",
        "userName": "丁锦婷",
        "postName": "接口开发",
        "duty": null,
        "sex": "2",
        "userIdInt": 1290,
        "deptId": 15,
        "groupId": 139
      },
      {
        "id": 664,
        "userId": "sgh1299",
        "userName": "邵桂红",
        "postName": "接口开发",
        "duty": null,
        "sex": "2",
        "userIdInt": 1299,
        "deptId": 15,
        "groupId": 139
      },
      {
        "id": 884,
        "userId": "ysf1492",
        "userName": "尹少凡",
        "postName": "接口开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1492,
        "deptId": 15,
        "groupId": 139
      }
    ],
    "userNums": 4,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "姚锋"
  },
  {
    "id": 32,
    "name": "行情组",
    "code": "003004",
    "parentId": 16,
    "path": ",0,15,16,32,",
    "manager": "dwh1281",
    "orderNo": 4,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 74,
        "userId": "tjx409",
        "userName": "唐建新",
        "postName": "Delphi开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 409,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 331,
        "userId": "wj1080",
        "userName": "王江",
        "postName": "Delphi开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1080,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 647,
        "userId": "dwh1281",
        "userName": "董文华",
        "postName": "研发主管",
        "duty": null,
        "sex": "1",
        "userIdInt": 1281,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 667,
        "userId": "sw1302",
        "userName": "孙炜",
        "postName": "Delphi开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1302,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 773,
        "userId": "zqr1383",
        "userName": "庄千荣",
        "postName": "Delphi开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1383,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 899,
        "userId": "lsz1508",
        "userName": "楼申中",
        "postName": "Delphi开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1508,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 916,
        "userId": "cyq1524",
        "userName": "陈元奇",
        "postName": "C++开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1524,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 920,
        "userId": "lsw1528",
        "userName": "林书文",
        "postName": "Delphi开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1528,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 933,
        "userId": "lz1541",
        "userName": "李卓",
        "postName": "C++开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1541,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 958,
        "userId": "yjj1561",
        "userName": "杨俊杰",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1561,
        "deptId": 15,
        "groupId": 32
      },
      {
        "id": 962,
        "userId": "xxt1565",
        "userName": "许秀婷",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1565,
        "deptId": 15,
        "groupId": 32
      }
    ],
    "userNums": 11,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "董文华"
  },
  {
    "id": 17,
    "name": "客户端业务组",
    "code": "003006",
    "parentId": 15,
    "path": ",0,15,17,",
    "manager": "yjp034",
    "orderNo": 5,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 36,
        "userId": "wlz346",
        "userName": "王路子",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 346,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 75,
        "userId": "zl704",
        "userName": "钟露",
        "postName": "技术经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 704,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 517,
        "userId": "xql1166",
        "userName": "谢青仂",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1166,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 658,
        "userId": "lcj1293",
        "userName": "李超杰",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1293,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 666,
        "userId": "rp1301",
        "userName": "阮鹏",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1301,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 696,
        "userId": "zch1322",
        "userName": "张成虎",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1322,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 878,
        "userId": "zkz1488",
        "userName": "张凯泽",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1488,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 894,
        "userId": "wsh1502",
        "userName": "王书恒",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1502,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 901,
        "userId": "wl1510",
        "userName": "王林",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1510,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 910,
        "userId": "zzt1518",
        "userName": "周振霆",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1518,
        "deptId": 15,
        "groupId": 17
      },
      {
        "id": 952,
        "userId": "dxm1555",
        "userName": "丁宪敏",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1555,
        "deptId": 15,
        "groupId": 17
      }
    ],
    "userNums": 11,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "殷金鹏"
  },
  {
    "id": 105,
    "name": "创新业务部",
    "code": "003007",
    "parentId": 15,
    "path": ",0,15,105,",
    "manager": "wdz1408",
    "orderNo": 6,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2019-12-31 04:47:23",
    "updateTime": null,
    "userList": [
      {
        "id": 583,
        "userId": "xrw1227",
        "userName": "徐仁为",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1227,
        "deptId": 15,
        "groupId": 105
      },
      {
        "id": 724,
        "userId": "zps1350",
        "userName": "赵盘石",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1350,
        "deptId": 15,
        "groupId": 105
      }
    ],
    "userNums": 2,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "王得志"
  },
  {
    "id": 184,
    "name": "前端组",
    "code": "003007002",
    "parentId": 105,
    "path": ",0,15,105,184,",
    "manager": "zps1350",
    "orderNo": 2,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-03-09 02:59:03",
    "updateTime": null,
    "userList": [
      {
        "id": 615,
        "userId": "gy1250",
        "userName": "甘雨",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1250,
        "deptId": 15,
        "groupId": 184
      },
      {
        "id": 651,
        "userId": "wwt1286",
        "userName": "王文涛Y",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1286,
        "deptId": 15,
        "groupId": 184
      },
      {
        "id": 661,
        "userId": "zhy1296",
        "userName": "赵焕玉",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1296,
        "deptId": 15,
        "groupId": 184
      },
      {
        "id": 678,
        "userId": "xw1313",
        "userName": "谢伟",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1313,
        "deptId": 15,
        "groupId": 184
      },
      {
        "id": 861,
        "userId": "lyq1471",
        "userName": "鲁友前",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1471,
        "deptId": 15,
        "groupId": 184
      },
      {
        "id": 949,
        "userId": "lj1553",
        "userName": "罗军",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1553,
        "deptId": 15,
        "groupId": 184
      }
    ],
    "userNums": 6,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "赵盘石"
  },
  {
    "id": 185,
    "name": "后台1组",
    "code": "003007003",
    "parentId": 105,
    "path": ",0,15,105,185,",
    "manager": "xrw1227",
    "orderNo": 3,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-03-09 02:59:25",
    "updateTime": null,
    "userList": [
      {
        "id": 612,
        "userId": "cy1248",
        "userName": "陈勇",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1248,
        "deptId": 15,
        "groupId": 185
      },
      {
        "id": 797,
        "userId": "kx1406",
        "userName": "柯希",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1406,
        "deptId": 15,
        "groupId": 185
      },
      {
        "id": 842,
        "userId": "lwd1452",
        "userName": "刘伟栋",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1452,
        "deptId": 15,
        "groupId": 185
      },
      {
        "id": 850,
        "userId": "wjh1460",
        "userName": "王建辉",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1460,
        "deptId": 15,
        "groupId": 185
      },
      {
        "id": 948,
        "userId": "hss1552",
        "userName": "何森森",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1552,
        "deptId": 15,
        "groupId": 185
      }
    ],
    "userNums": 5,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "徐仁为"
  },
  {
    "id": 198,
    "name": "后台2组",
    "code": "003007004",
    "parentId": 105,
    "path": ",0,15,105,198,",
    "manager": "wdz1408",
    "orderNo": 4,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2022-06-20 03:24:39",
    "updateTime": null,
    "userList": [
      {
        "id": 806,
        "userId": "yrx1415",
        "userName": "杨瑞鑫",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1415,
        "deptId": 15,
        "groupId": 198
      },
      {
        "id": 895,
        "userId": "sy1504",
        "userName": "尚宇",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1504,
        "deptId": 15,
        "groupId": 198
      },
      {
        "id": 925,
        "userId": "lcn1533",
        "userName": "李晨楠",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1533,
        "deptId": 15,
        "groupId": 198
      },
      {
        "id": 928,
        "userId": "cxh1536",
        "userName": "操欣煌",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1536,
        "deptId": 15,
        "groupId": 198
      },
      {
        "id": 934,
        "userId": "whj1543",
        "userName": "吴杭洁",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1543,
        "deptId": 15,
        "groupId": 198
      }
    ],
    "userNums": 5,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "王得志"
  },
  {
    "id": 5,
    "name": "行政部",
    "code": "004",
    "parentId": 0,
    "path": ",0,5,",
    "manager": "zyl016",
    "orderNo": 4,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 198,
        "userId": "zyl016",
        "userName": "朱永蕾",
        "postName": "行政总监",
        "duty": null,
        "sex": "2",
        "userIdInt": 16,
        "deptId": 5,
        "groupId": 5
      },
      {
        "id": 197,
        "userId": "pd703",
        "userName": "潘迪",
        "postName": "行政",
        "duty": null,
        "sex": "2",
        "userIdInt": 703,
        "deptId": 5,
        "groupId": 5
      },
      {
        "id": 199,
        "userId": "ylf902",
        "userName": "喻利芳",
        "postName": "行政",
        "duty": null,
        "sex": "2",
        "userIdInt": 902,
        "deptId": 5,
        "groupId": 5
      },
      {
        "id": 375,
        "userId": "ln1124",
        "userName": "李喃",
        "postName": "行政",
        "duty": null,
        "sex": "2",
        "userIdInt": 1124,
        "deptId": 5,
        "groupId": 5
      }
    ],
    "userNums": 4,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "朱永蕾"
  },
  {
    "id": 100,
    "name": "技术服务部",
    "code": "005",
    "parentId": 0,
    "path": ",0,100,",
    "manager": "pjl008",
    "orderNo": 5,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2019-01-23 09:00:24",
    "updateTime": null,
    "userList": [
      {
        "id": 2,
        "userId": "pjl008",
        "userName": "庞继亮",
        "postName": "部门经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 8,
        "deptId": 100,
        "groupId": 100
      },
      {
        "id": 48,
        "userId": "xj804",
        "userName": "谢健",
        "postName": "技术经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 804,
        "deptId": 100,
        "groupId": 100
      }
    ],
    "userNums": 2,
    "deputyGeneral": "lgq817",
    "deputyGeneralName": "柳刚强",
    "managerName": "庞继亮"
  },
  {
    "id": 168,
    "name": "杭州团队",
    "code": "005001",
    "parentId": 100,
    "path": ",0,100,168,",
    "manager": "pjl008",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-08-28 07:57:30",
    "updateTime": null,
    "userList": [
      {
        "id": 283,
        "userId": "zsl1100",
        "userName": "周少龙",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1100,
        "deptId": 100,
        "groupId": 168
      },
      {
        "id": 581,
        "userId": "prz1225",
        "userName": "彭仁志",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1225,
        "deptId": 100,
        "groupId": 168
      },
      {
        "id": 618,
        "userId": "qxy1254",
        "userName": "齐旭云",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1254,
        "deptId": 100,
        "groupId": 168
      },
      {
        "id": 628,
        "userId": "tyx1266",
        "userName": "田亚旭",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1266,
        "deptId": 100,
        "groupId": 168
      },
      {
        "id": 906,
        "userId": "wjy1514",
        "userName": "王介艳",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1514,
        "deptId": 100,
        "groupId": 168
      },
      {
        "id": 951,
        "userId": "sl1554",
        "userName": "沈磊",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1554,
        "deptId": 100,
        "groupId": 168
      }
    ],
    "userNums": 6,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "庞继亮"
  },
  {
    "id": 169,
    "name": "深圳团队",
    "code": "005002",
    "parentId": 100,
    "path": ",0,100,169,",
    "manager": "xj804",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-08-28 07:58:11",
    "updateTime": null,
    "userList": [
      {
        "id": 284,
        "userId": "lls1101",
        "userName": "刘林森",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1101,
        "deptId": 100,
        "groupId": 169
      },
      {
        "id": 398,
        "userId": "lyb1139",
        "userName": "罗奕斌",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1139,
        "deptId": 100,
        "groupId": 169
      },
      {
        "id": 732,
        "userId": "lz1358",
        "userName": "李筝",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1358,
        "deptId": 100,
        "groupId": 169
      },
      {
        "id": 743,
        "userId": "ycf1368",
        "userName": "叶朝丰",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1368,
        "deptId": 100,
        "groupId": 169
      }
    ],
    "userNums": 4,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "谢健"
  },
  {
    "id": 190,
    "name": "Android团队",
    "code": "005002001",
    "parentId": 169,
    "path": ",0,100,169,190,",
    "manager": "lz1358",
    "orderNo": 1,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-10-11 09:24:12",
    "updateTime": null,
    "userList": [
      {
        "id": 786,
        "userId": "jr1397",
        "userName": "蒋荣",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1397,
        "deptId": 100,
        "groupId": 190
      },
      {
        "id": 849,
        "userId": "hcj1459",
        "userName": "胡昌杰",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1459,
        "deptId": 100,
        "groupId": 190
      },
      {
        "id": 874,
        "userId": "lj1484",
        "userName": "罗建",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1484,
        "deptId": 100,
        "groupId": 190
      },
      {
        "id": 888,
        "userId": "ll1497",
        "userName": "李林",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1497,
        "deptId": 100,
        "groupId": 190
      }
    ],
    "userNums": 4,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "李筝"
  },
  {
    "id": 191,
    "name": "iOS团队",
    "code": "005002002",
    "parentId": 169,
    "path": ",0,100,169,191,",
    "manager": "lyb1139",
    "orderNo": 2,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-10-11 09:24:48",
    "updateTime": null,
    "userList": [
      {
        "id": 631,
        "userId": "yq1263",
        "userName": "颜琪",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1263,
        "deptId": 100,
        "groupId": 191
      },
      {
        "id": 790,
        "userId": "qc1399",
        "userName": "覃创",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1399,
        "deptId": 100,
        "groupId": 191
      },
      {
        "id": 823,
        "userId": "hmx1432",
        "userName": "洪铭翔",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1432,
        "deptId": 100,
        "groupId": 191
      }
    ],
    "userNums": 3,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "罗奕斌"
  },
  {
    "id": 104,
    "name": "金融数据研究中心",
    "code": "006",
    "parentId": 0,
    "path": ",0,104,",
    "manager": "sj015",
    "orderNo": 6,
    "description": "数据研发及技术服务",
    "createUser": null,
    "updateUser": null,
    "createTime": "2019-11-27 08:50:06",
    "updateTime": null,
    "userList": [],
    "userNums": 0,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "孙杰"
  },
  {
    "id": 106,
    "name": "研发组",
    "code": "006001",
    "parentId": 104,
    "path": ",0,104,106,",
    "manager": "cjl996",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2019-12-31 04:53:58",
    "updateTime": null,
    "userList": [
      {
        "id": 13,
        "userId": "qyz728",
        "userName": "秦余钊",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 728,
        "deptId": 104,
        "groupId": 106
      },
      {
        "id": 234,
        "userId": "cjl996",
        "userName": "陈加良",
        "postName": "研发主管",
        "duty": null,
        "sex": "1",
        "userIdInt": 996,
        "deptId": 104,
        "groupId": 106
      },
      {
        "id": 367,
        "userId": "wgz1116",
        "userName": "王光钊",
        "postName": "Python开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1116,
        "deptId": 104,
        "groupId": 106
      },
      {
        "id": 393,
        "userId": "yzl1137",
        "userName": "闫志龙",
        "postName": "Python开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1137,
        "deptId": 104,
        "groupId": 106
      },
      {
        "id": 737,
        "userId": "dhj1363",
        "userName": "段浩杰",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1363,
        "deptId": 104,
        "groupId": 106
      }
    ],
    "userNums": 5,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "陈加良"
  },
  {
    "id": 164,
    "name": "研发1组",
    "code": "006001001",
    "parentId": 106,
    "path": ",0,104,106,164,",
    "manager": "cjl996",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-30 10:48:34",
    "updateTime": null,
    "userList": [
      {
        "id": 262,
        "userId": "ghf1018",
        "userName": "郭洪飞",
        "postName": "Python开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1018,
        "deptId": 104,
        "groupId": 164
      },
      {
        "id": 413,
        "userId": "hyl1153",
        "userName": "黄益銮",
        "postName": "Python开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1153,
        "deptId": 104,
        "groupId": 164
      },
      {
        "id": 634,
        "userId": "gxr1268",
        "userName": "郭鑫瑞",
        "postName": "Python开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1268,
        "deptId": 104,
        "groupId": 164
      },
      {
        "id": 935,
        "userId": "hp1542",
        "userName": "胡培",
        "postName": "大数据开发",
        "duty": "大数据开发",
        "sex": "1",
        "userIdInt": 1542,
        "deptId": 104,
        "groupId": 164
      }
    ],
    "userNums": 4,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "陈加良"
  },
  {
    "id": 165,
    "name": "研发2组",
    "code": "006001002",
    "parentId": 106,
    "path": ",0,104,106,165,",
    "manager": "yzl1137",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-30 10:49:02",
    "updateTime": null,
    "userList": [
      {
        "id": 654,
        "userId": "lty1289",
        "userName": "林天宇",
        "postName": "Python开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1289,
        "deptId": 104,
        "groupId": 165
      }
    ],
    "userNums": 1,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "闫志龙"
  },
  {
    "id": 166,
    "name": "研发3组",
    "code": "006001003",
    "parentId": 106,
    "path": ",0,104,106,166,",
    "manager": "wgz1116",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-30 10:49:28",
    "updateTime": null,
    "userList": [
      {
        "id": 718,
        "userId": "zzm1344",
        "userName": "赵志明",
        "postName": "Python开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1344,
        "deptId": 104,
        "groupId": 166
      },
      {
        "id": 815,
        "userId": "zzm1424",
        "userName": "赵泽满",
        "postName": "Python开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1424,
        "deptId": 104,
        "groupId": 166
      }
    ],
    "userNums": 2,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "王光钊"
  },
  {
    "id": 188,
    "name": "研发4组",
    "code": "006001004",
    "parentId": 106,
    "path": ",0,104,106,188,",
    "manager": "qyz728",
    "orderNo": 4,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-06-21 04:57:06",
    "updateTime": null,
    "userList": [
      {
        "id": 41,
        "userId": "lxl838",
        "userName": "刘学利",
        "postName": "前端开发",
        "duty": "",
        "sex": "2",
        "userIdInt": 838,
        "deptId": 104,
        "groupId": 188
      },
      {
        "id": 411,
        "userId": "wjj1152",
        "userName": "魏睛睛",
        "postName": "前端开发",
        "duty": "",
        "sex": "2",
        "userIdInt": 1152,
        "deptId": 104,
        "groupId": 188
      },
      {
        "id": 820,
        "userId": "zm1429",
        "userName": "张明",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1429,
        "deptId": 104,
        "groupId": 188
      },
      {
        "id": 959,
        "userId": "sjj1562",
        "userName": "宋晶晶",
        "postName": "前端开发",
        "duty": "",
        "sex": "2",
        "userIdInt": 1562,
        "deptId": 104,
        "groupId": 188
      }
    ],
    "userNums": 4,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "秦余钊"
  },
  {
    "id": 108,
    "name": "产品组",
    "code": "006002",
    "parentId": 104,
    "path": ",0,104,108,",
    "manager": "sj015",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2019-12-31 04:54:24",
    "updateTime": null,
    "userList": [
      {
        "id": 907,
        "userId": "zsr1515",
        "userName": "郑思锐",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1515,
        "deptId": 104,
        "groupId": 108
      },
      {
        "id": 950,
        "userId": "zjc1551",
        "userName": "张杰诚",
        "postName": "产品经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1551,
        "deptId": 104,
        "groupId": 108
      }
    ],
    "userNums": 2,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "孙杰"
  },
  {
    "id": 8,
    "name": "开发部",
    "code": "007",
    "parentId": 0,
    "path": ",0,8,",
    "manager": "gdl744",
    "orderNo": 7,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 4,
        "userId": "gdl744",
        "userName": "龚栋亮",
        "postName": "部门经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 744,
        "deptId": 8,
        "groupId": 8
      },
      {
        "id": 46,
        "userId": "lx780",
        "userName": "李轩",
        "postName": "部门副经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 780,
        "deptId": 8,
        "groupId": 8
      },
      {
        "id": 67,
        "userId": "zzy865",
        "userName": "郑知远",
        "postName": "项目经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 865,
        "deptId": 8,
        "groupId": 8
      },
      {
        "id": 153,
        "userId": "cyh939",
        "userName": "陈燕慧",
        "postName": "测试主管",
        "duty": null,
        "sex": "2",
        "userIdInt": 939,
        "deptId": 8,
        "groupId": 8
      }
    ],
    "userNums": 4,
    "deputyGeneral": "lgq817",
    "deputyGeneralName": "柳刚强",
    "managerName": "龚栋亮"
  },
  {
    "id": 10,
    "name": "开发一部",
    "code": "007001",
    "parentId": 8,
    "path": ",0,8,10,",
    "manager": "zzy865",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [],
    "userNums": 0,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "郑知远"
  },
  {
    "id": 159,
    "name": "一部1组",
    "code": "007001001",
    "parentId": 10,
    "path": ",0,8,10,159,",
    "manager": "zzy865",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-30 08:24:12",
    "updateTime": null,
    "userList": [
      {
        "id": 310,
        "userId": "hdw1055",
        "userName": "黄杜威",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1055,
        "deptId": 8,
        "groupId": 159
      },
      {
        "id": 423,
        "userId": "qyj1160",
        "userName": "钱勇局",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1160,
        "deptId": 8,
        "groupId": 159
      },
      {
        "id": 627,
        "userId": "wxh1260",
        "userName": "王小辉",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1260,
        "deptId": 8,
        "groupId": 159
      },
      {
        "id": 716,
        "userId": "lmq1342",
        "userName": "刘明强",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1342,
        "deptId": 8,
        "groupId": 159
      },
      {
        "id": 777,
        "userId": "zt1386",
        "userName": "朱涛",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1386,
        "deptId": 8,
        "groupId": 159
      },
      {
        "id": 778,
        "userId": "gm1387",
        "userName": "龚敏",
        "postName": "前端开发",
        "duty": "",
        "sex": "2",
        "userIdInt": 1387,
        "deptId": 8,
        "groupId": 159
      },
      {
        "id": 835,
        "userId": "pjq1445",
        "userName": "潘俊清",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1445,
        "deptId": 8,
        "groupId": 159
      }
    ],
    "userNums": 7,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "郑知远"
  },
  {
    "id": 189,
    "name": "一部2组",
    "code": "007001002",
    "parentId": 10,
    "path": ",0,8,10,189,",
    "manager": "jgy1120",
    "orderNo": 2,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-08-13 09:53:06",
    "updateTime": null,
    "userList": [
      {
        "id": 112,
        "userId": "fw894",
        "userName": "冯维",
        "postName": "前端开发",
        "duty": "",
        "sex": "2",
        "userIdInt": 894,
        "deptId": 8,
        "groupId": 189
      },
      {
        "id": 369,
        "userId": "jgy1120",
        "userName": "季国勇",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1120,
        "deptId": 8,
        "groupId": 189
      },
      {
        "id": 600,
        "userId": "yqy1240",
        "userName": "叶乾阳",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1240,
        "deptId": 8,
        "groupId": 189
      },
      {
        "id": 788,
        "userId": "hkl1395",
        "userName": "黄奎泷",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1395,
        "deptId": 8,
        "groupId": 189
      },
      {
        "id": 837,
        "userId": "jnt1447",
        "userName": "姜宁桃",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1447,
        "deptId": 8,
        "groupId": 189
      }
    ],
    "userNums": 5,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "季国勇"
  },
  {
    "id": 171,
    "name": "开发二、三、四部",
    "code": "007002",
    "parentId": 8,
    "path": ",0,8,171,",
    "manager": "lx780",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-08-28 09:40:07",
    "updateTime": null,
    "userList": [],
    "userNums": 0,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "李轩"
  },
  {
    "id": 12,
    "name": "开发二部",
    "code": "007002001",
    "parentId": 171,
    "path": ",0,8,12,171,",
    "manager": "lx780",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 27,
        "userId": "lxy774",
        "userName": "吕小勇",
        "postName": "项目经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 774,
        "deptId": 8,
        "groupId": 12
      },
      {
        "id": 31,
        "userId": "plf825",
        "userName": "潘龙飞",
        "postName": "项目经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 825,
        "deptId": 8,
        "groupId": 12
      },
      {
        "id": 255,
        "userId": "lzy1014",
        "userName": "柳兆勇",
        "postName": "项目经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1014,
        "deptId": 8,
        "groupId": 12
      }
    ],
    "userNums": 3,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "李轩"
  },
  {
    "id": 135,
    "name": "二部1组",
    "code": "007002001001",
    "parentId": 12,
    "path": ",0,8,12,135,171,",
    "manager": "lzy1014",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:52:24",
    "updateTime": null,
    "userList": [
      {
        "id": 785,
        "userId": "zw1394",
        "userName": "周伟",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1394,
        "deptId": 8,
        "groupId": 135
      },
      {
        "id": 802,
        "userId": "znt1411",
        "userName": "庄娘添",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1411,
        "deptId": 8,
        "groupId": 135
      },
      {
        "id": 876,
        "userId": "wc1486",
        "userName": "王冲",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1486,
        "deptId": 8,
        "groupId": 135
      },
      {
        "id": 921,
        "userId": "yrj1529",
        "userName": "乐锐君",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1529,
        "deptId": 8,
        "groupId": 135
      }
    ],
    "userNums": 4,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "柳兆勇"
  },
  {
    "id": 180,
    "name": "二部2组",
    "code": "007002001002",
    "parentId": 12,
    "path": ",0,8,12,171,180,",
    "manager": "lxy774",
    "orderNo": 2,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-02-24 07:35:47",
    "updateTime": null,
    "userList": [
      {
        "id": 125,
        "userId": "lcg898",
        "userName": "刘长广",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 898,
        "deptId": 8,
        "groupId": 180
      },
      {
        "id": 596,
        "userId": "yjw1238",
        "userName": "杨军伟",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1238,
        "deptId": 8,
        "groupId": 180
      },
      {
        "id": 789,
        "userId": "wm1398",
        "userName": "吴铭",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1398,
        "deptId": 8,
        "groupId": 180
      },
      {
        "id": 832,
        "userId": "cxm1442",
        "userName": "陈显明",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1442,
        "deptId": 8,
        "groupId": 180
      },
      {
        "id": 853,
        "userId": "nj1463",
        "userName": "牛晋",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1463,
        "deptId": 8,
        "groupId": 180
      },
      {
        "id": 854,
        "userId": "ljr1464",
        "userName": "刘洁茹",
        "postName": "前端开发",
        "duty": "",
        "sex": "2",
        "userIdInt": 1464,
        "deptId": 8,
        "groupId": 180
      },
      {
        "id": 870,
        "userId": "yc1480",
        "userName": "杨闯",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1480,
        "deptId": 8,
        "groupId": 180
      }
    ],
    "userNums": 7,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "吕小勇"
  },
  {
    "id": 181,
    "name": "东北项目组",
    "code": "007002001002001",
    "parentId": 180,
    "path": ",0,8,12,171,180,181,",
    "manager": "yjw1238",
    "orderNo": 999,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-02-24 07:36:58",
    "updateTime": null,
    "userList": [
      {
        "id": 292,
        "userId": "xcy1037",
        "userName": "薛传炀",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1037,
        "deptId": 8,
        "groupId": 181
      },
      {
        "id": 307,
        "userId": "lhw1052",
        "userName": "罗海威",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1052,
        "deptId": 8,
        "groupId": 181
      },
      {
        "id": 648,
        "userId": "py1282",
        "userName": "潘琰",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1282,
        "deptId": 8,
        "groupId": 181
      },
      {
        "id": 741,
        "userId": "hpp1367",
        "userName": "何平平",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1367,
        "deptId": 8,
        "groupId": 181
      },
      {
        "id": 824,
        "userId": "wzq1433",
        "userName": "魏战强",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1433,
        "deptId": 8,
        "groupId": 181
      },
      {
        "id": 871,
        "userId": "zwt1481",
        "userName": "张婉婷",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1481,
        "deptId": 8,
        "groupId": 181
      },
      {
        "id": 887,
        "userId": "hpw1496",
        "userName": "何沛文",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1496,
        "deptId": 8,
        "groupId": 181
      },
      {
        "id": 891,
        "userId": "ljn1501",
        "userName": "李佳楠",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1501,
        "deptId": 8,
        "groupId": 181
      },
      {
        "id": 936,
        "userId": "zyy1544",
        "userName": "赵云云",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1544,
        "deptId": 8,
        "groupId": 181
      }
    ],
    "userNums": 9,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "杨军伟"
  },
  {
    "id": 195,
    "name": "二部3组",
    "code": "007002001003",
    "parentId": 12,
    "path": ",0,8,12,171,195,",
    "manager": "plf825",
    "orderNo": 3,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2022-02-17 02:51:43",
    "updateTime": null,
    "userList": [
      {
        "id": 570,
        "userId": "grj1214",
        "userName": "谷荣景",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1214,
        "deptId": 8,
        "groupId": 195
      },
      {
        "id": 833,
        "userId": "ssj1443",
        "userName": "沈胜杰",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1443,
        "deptId": 8,
        "groupId": 195
      },
      {
        "id": 880,
        "userId": "lxj1490",
        "userName": "李晓健",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1490,
        "deptId": 8,
        "groupId": 195
      },
      {
        "id": 909,
        "userId": "kx1517",
        "userName": "康欣",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1517,
        "deptId": 8,
        "groupId": 195
      },
      {
        "id": 922,
        "userId": "lzj1530",
        "userName": "李中杰",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1530,
        "deptId": 8,
        "groupId": 195
      }
    ],
    "userNums": 5,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "潘龙飞"
  },
  {
    "id": 20,
    "name": "开发三部",
    "code": "007002002",
    "parentId": 171,
    "path": ",0,8,20,171,",
    "manager": "lq956",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 176,
        "userId": "lq956",
        "userName": "刘强",
        "postName": "项目经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 956,
        "deptId": 8,
        "groupId": 20
      }
    ],
    "userNums": 1,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "刘强"
  },
  {
    "id": 141,
    "name": "三部1组",
    "code": "007002002001",
    "parentId": 20,
    "path": ",0,8,20,141,171,",
    "manager": "wxk1107",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:54:15",
    "updateTime": null,
    "userList": [
      {
        "id": 313,
        "userId": "yf1062",
        "userName": "杨飞",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1062,
        "deptId": 8,
        "groupId": 141
      },
      {
        "id": 314,
        "userId": "bmh1063",
        "userName": "鲍旻昊",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1063,
        "deptId": 8,
        "groupId": 141
      },
      {
        "id": 355,
        "userId": "wxk1107",
        "userName": "王锡凯",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1107,
        "deptId": 8,
        "groupId": 141
      },
      {
        "id": 606,
        "userId": "wxf1242",
        "userName": "吴雪飞",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1242,
        "deptId": 8,
        "groupId": 141
      },
      {
        "id": 930,
        "userId": "ssf1538",
        "userName": "施上浮",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1538,
        "deptId": 8,
        "groupId": 141
      },
      {
        "id": 943,
        "userId": "apf1549",
        "userName": "艾平飞",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1549,
        "deptId": 8,
        "groupId": 141
      }
    ],
    "userNums": 6,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "王锡凯"
  },
  {
    "id": 138,
    "name": "三部2组",
    "code": "007002002002",
    "parentId": 20,
    "path": ",0,8,20,138,171,",
    "manager": "cc815",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:53:29",
    "updateTime": null,
    "userList": [
      {
        "id": 44,
        "userId": "zjx762",
        "userName": "朱金鑫",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 762,
        "deptId": 8,
        "groupId": 138
      },
      {
        "id": 49,
        "userId": "cc815",
        "userName": "陈闯",
        "postName": "项目经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 815,
        "deptId": 8,
        "groupId": 138
      },
      {
        "id": 551,
        "userId": "zjd1196",
        "userName": "张佳栋",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1196,
        "deptId": 8,
        "groupId": 138
      },
      {
        "id": 566,
        "userId": "zb1208",
        "userName": "朱斌",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1208,
        "deptId": 8,
        "groupId": 138
      },
      {
        "id": 746,
        "userId": "ybf1372",
        "userName": "叶兵锋",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1372,
        "deptId": 8,
        "groupId": 138
      },
      {
        "id": 827,
        "userId": "gkp1437",
        "userName": "顾昆鹏",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1437,
        "deptId": 8,
        "groupId": 138
      },
      {
        "id": 846,
        "userId": "yg1456",
        "userName": "杨光",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1456,
        "deptId": 8,
        "groupId": 138
      },
      {
        "id": 961,
        "userId": "wyc1564",
        "userName": "王育晨",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1564,
        "deptId": 8,
        "groupId": 138
      }
    ],
    "userNums": 8,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "陈闯"
  },
  {
    "id": 140,
    "name": "三部3组",
    "code": "007002002003",
    "parentId": 20,
    "path": ",0,8,20,140,171,",
    "manager": "sms1017",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:53:50",
    "updateTime": null,
    "userList": [
      {
        "id": 53,
        "userId": "yt864",
        "userName": "袁婷",
        "postName": "前端开发",
        "duty": "",
        "sex": "2",
        "userIdInt": 864,
        "deptId": 8,
        "groupId": 140
      },
      {
        "id": 260,
        "userId": "sms1017",
        "userName": "宋茂森",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1017,
        "deptId": 8,
        "groupId": 140
      },
      {
        "id": 780,
        "userId": "yj1389",
        "userName": "叶炯",
        "postName": "iOS开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1389,
        "deptId": 8,
        "groupId": 140
      },
      {
        "id": 864,
        "userId": "shr1474",
        "userName": "单海瑞",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1474,
        "deptId": 8,
        "groupId": 140
      },
      {
        "id": 886,
        "userId": "jrw1495",
        "userName": "金荣伟",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1495,
        "deptId": 8,
        "groupId": 140
      },
      {
        "id": 964,
        "userId": "zts1567",
        "userName": "张同胜",
        "postName": "Android开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1567,
        "deptId": 8,
        "groupId": 140
      }
    ],
    "userNums": 6,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "宋茂森"
  },
  {
    "id": 23,
    "name": "开发四部",
    "code": "007002003",
    "parentId": 171,
    "path": ",0,8,23,171,",
    "manager": "hhz819",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 55,
        "userId": "hhz819",
        "userName": "黄海珠",
        "postName": "技术经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 819,
        "deptId": 8,
        "groupId": 23
      },
      {
        "id": 545,
        "userId": "ysh1191",
        "userName": "姚思航",
        "postName": "前端开发",
        "duty": "",
        "sex": "2",
        "userIdInt": 1191,
        "deptId": 8,
        "groupId": 23
      },
      {
        "id": 768,
        "userId": "ptw1378",
        "userName": "彭泰玮",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1378,
        "deptId": 8,
        "groupId": 23
      },
      {
        "id": 779,
        "userId": "lh1388",
        "userName": "林浩",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1388,
        "deptId": 8,
        "groupId": 23
      },
      {
        "id": 809,
        "userId": "hf1418",
        "userName": "何风",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1418,
        "deptId": 8,
        "groupId": 23
      },
      {
        "id": 913,
        "userId": "cqf1521",
        "userName": "陈求锋",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1521,
        "deptId": 8,
        "groupId": 23
      },
      {
        "id": 968,
        "userId": "cy1571",
        "userName": "崔渝",
        "postName": "前端开发",
        "duty": "",
        "sex": "1",
        "userIdInt": 1571,
        "deptId": 8,
        "groupId": 23
      }
    ],
    "userNums": 7,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "黄海珠"
  },
  {
    "id": 34,
    "name": "测试组",
    "code": "007003",
    "parentId": 8,
    "path": ",0,8,34,",
    "manager": "cyh939",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [],
    "userNums": 0,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "陈燕慧"
  },
  {
    "id": 160,
    "name": "测试1组",
    "code": "007003001",
    "parentId": 34,
    "path": ",0,8,34,160,",
    "manager": "dl1311",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-30 08:28:19",
    "updateTime": null,
    "userList": [
      {
        "id": 665,
        "userId": "zjz1300",
        "userName": "詹金庄",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1300,
        "deptId": 8,
        "groupId": 160
      },
      {
        "id": 676,
        "userId": "dl1311",
        "userName": "丁林",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1311,
        "deptId": 8,
        "groupId": 160
      },
      {
        "id": 801,
        "userId": "cpd1410",
        "userName": "陈培铎",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1410,
        "deptId": 8,
        "groupId": 160
      },
      {
        "id": 873,
        "userId": "xjy1483",
        "userName": "谢锦尧",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1483,
        "deptId": 8,
        "groupId": 160
      },
      {
        "id": 900,
        "userId": "oyl1509",
        "userName": "欧阳琳",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1509,
        "deptId": 8,
        "groupId": 160
      },
      {
        "id": 917,
        "userId": "cg1525",
        "userName": "陈刚",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1525,
        "deptId": 8,
        "groupId": 160
      }
    ],
    "userNums": 6,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "丁林"
  },
  {
    "id": 161,
    "name": "测试2组",
    "code": "007003002",
    "parentId": 34,
    "path": ",0,8,34,161,",
    "manager": "ghy1128",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-30 08:28:55",
    "updateTime": null,
    "userList": [
      {
        "id": 224,
        "userId": "wxj986",
        "userName": "吴晓君",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 986,
        "deptId": 8,
        "groupId": 161
      },
      {
        "id": 374,
        "userId": "ghy1128",
        "userName": "郜慧毅",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1128,
        "deptId": 8,
        "groupId": 161
      },
      {
        "id": 630,
        "userId": "zjb1262",
        "userName": "张钧博",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1262,
        "deptId": 8,
        "groupId": 161
      },
      {
        "id": 822,
        "userId": "kxy1431",
        "userName": "孔向阳",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1431,
        "deptId": 8,
        "groupId": 161
      },
      {
        "id": 889,
        "userId": "cjm1499",
        "userName": "曹俊明",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1499,
        "deptId": 8,
        "groupId": 161
      },
      {
        "id": 904,
        "userId": "wwt1512",
        "userName": "王文涛K",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1512,
        "deptId": 8,
        "groupId": 161
      },
      {
        "id": 954,
        "userId": "wxx1557",
        "userName": "王茜茜",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1557,
        "deptId": 8,
        "groupId": 161
      }
    ],
    "userNums": 7,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "郜慧毅"
  },
  {
    "id": 162,
    "name": "测试3组",
    "code": "007003003",
    "parentId": 34,
    "path": ",0,8,34,162,",
    "manager": "hy1288",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-30 08:29:22",
    "updateTime": null,
    "userList": [
      {
        "id": 652,
        "userId": "zyz1287",
        "userName": "赵玉忠",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1287,
        "deptId": 8,
        "groupId": 162
      },
      {
        "id": 653,
        "userId": "hy1288",
        "userName": "韩媛",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1288,
        "deptId": 8,
        "groupId": 162
      },
      {
        "id": 691,
        "userId": "zzj1317",
        "userName": "周籽敬",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1317,
        "deptId": 8,
        "groupId": 162
      },
      {
        "id": 893,
        "userId": "swd1503",
        "userName": "施伟冬",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1503,
        "deptId": 8,
        "groupId": 162
      },
      {
        "id": 902,
        "userId": "jss1511",
        "userName": "贾松松",
        "postName": "测试",
        "duty": null,
        "sex": "1",
        "userIdInt": 1511,
        "deptId": 8,
        "groupId": 162
      },
      {
        "id": 926,
        "userId": "wjh1534",
        "userName": "王佳慧",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1534,
        "deptId": 8,
        "groupId": 162
      },
      {
        "id": 940,
        "userId": "ylx1546",
        "userName": "杨丽雪",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1546,
        "deptId": 8,
        "groupId": 162
      },
      {
        "id": 963,
        "userId": "xy1566",
        "userName": "西莹",
        "postName": "测试",
        "duty": null,
        "sex": "2",
        "userIdInt": 1566,
        "deptId": 8,
        "groupId": 162
      }
    ],
    "userNums": 8,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "韩媛"
  },
  {
    "id": 6,
    "name": "人力资源部",
    "code": "008",
    "parentId": 0,
    "path": ",0,6,",
    "manager": "lgp090",
    "orderNo": 8,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 123,
        "userId": "lgp090",
        "userName": "李国平",
        "postName": "人力资源总监",
        "duty": null,
        "sex": "1",
        "userIdInt": 90,
        "deptId": 6,
        "groupId": 6
      },
      {
        "id": 186,
        "userId": "jiakl806",
        "userName": "贾锴莉",
        "postName": "人力资源主管",
        "duty": null,
        "sex": "2",
        "userIdInt": 806,
        "deptId": 6,
        "groupId": 6
      },
      {
        "id": 289,
        "userId": "jsq1034",
        "userName": "金胜权",
        "postName": "人力资源",
        "duty": "",
        "sex": "2",
        "userIdInt": 1034,
        "deptId": 6,
        "groupId": 6
      },
      {
        "id": 304,
        "userId": "zqq1096",
        "userName": "张倩倩",
        "postName": "人力资源",
        "duty": "",
        "sex": "2",
        "userIdInt": 1096,
        "deptId": 6,
        "groupId": 6
      }
    ],
    "userNums": 4,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "李国平"
  },
  {
    "id": 196,
    "name": "人力资源",
    "code": "008001",
    "parentId": 6,
    "path": ",0,6,196,",
    "manager": "jiakl806",
    "orderNo": 1,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2022-04-06 03:17:14",
    "updateTime": null,
    "userList": [],
    "userNums": 0,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "贾锴莉"
  },
  {
    "id": 197,
    "name": "外包挂靠",
    "code": "008002",
    "parentId": 6,
    "path": ",0,6,197,",
    "manager": "zqq1096",
    "orderNo": 2,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2022-04-26 09:04:33",
    "updateTime": null,
    "userList": [
      {
        "id": 866,
        "userId": "wh1476",
        "userName": "王豪",
        "postName": "Java开发",
        "duty": null,
        "sex": "1",
        "userIdInt": 1476,
        "deptId": 6,
        "groupId": 197
      }
    ],
    "userNums": 1,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "张倩倩"
  },
  {
    "id": 4,
    "name": "市场部",
    "code": "009",
    "parentId": 0,
    "path": ",0,4,",
    "manager": "lsq002",
    "orderNo": 9,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 285,
        "userId": "zyc23",
        "userName": "张玉成",
        "postName": "市场总监",
        "duty": "",
        "sex": "1",
        "userIdInt": 23,
        "deptId": 4,
        "groupId": 4
      },
      {
        "id": 241,
        "userId": "yuany24",
        "userName": "袁洋",
        "postName": "市场总监",
        "duty": "",
        "sex": "1",
        "userIdInt": 24,
        "deptId": 4,
        "groupId": 4
      }
    ],
    "userNums": 2,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "李烁权"
  },
  {
    "id": 119,
    "name": "深圳分公司",
    "code": "009001",
    "parentId": 4,
    "path": ",0,4,119,",
    "manager": "lih65",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:31:23",
    "updateTime": null,
    "userList": [
      {
        "id": 242,
        "userId": "lih65",
        "userName": "李浩",
        "postName": "市场总监",
        "duty": "",
        "sex": "1",
        "userIdInt": 65,
        "deptId": 4,
        "groupId": 119
      },
      {
        "id": 811,
        "userId": "ljw1420",
        "userName": "梁晋文",
        "postName": "商务经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1420,
        "deptId": 4,
        "groupId": 119
      }
    ],
    "userNums": 2,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "李浩"
  },
  {
    "id": 2,
    "name": "运维部",
    "code": "010",
    "parentId": 0,
    "path": ",0,2,",
    "manager": "sj015",
    "orderNo": 10,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 22,
        "userId": "sj015",
        "userName": "孙杰",
        "postName": "运维总监",
        "duty": null,
        "sex": "1",
        "userIdInt": 15,
        "deptId": 2,
        "groupId": 2
      }
    ],
    "userNums": 1,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "孙杰"
  },
  {
    "id": 111,
    "name": "运维监控",
    "code": "010001",
    "parentId": 2,
    "path": ",0,2,111,",
    "manager": "zyj853",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:23:48",
    "updateTime": null,
    "userList": [
      {
        "id": 32,
        "userId": "zyj853",
        "userName": "周耀杰",
        "postName": "运维主管",
        "duty": "",
        "sex": "1",
        "userIdInt": 853,
        "deptId": 2,
        "groupId": 111
      },
      {
        "id": 541,
        "userId": "ln1187",
        "userName": "李宁",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1187,
        "deptId": 2,
        "groupId": 111
      },
      {
        "id": 821,
        "userId": "yy1430",
        "userName": "杨永",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1430,
        "deptId": 2,
        "groupId": 111
      },
      {
        "id": 840,
        "userId": "wj1450",
        "userName": "王锦",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1450,
        "deptId": 2,
        "groupId": 111
      },
      {
        "id": 955,
        "userId": "yzg1558",
        "userName": "岳兆国",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1558,
        "deptId": 2,
        "groupId": 111
      },
      {
        "id": 966,
        "userId": "ldz1569",
        "userName": "柳东至",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1569,
        "deptId": 2,
        "groupId": 111
      }
    ],
    "userNums": 6,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "周耀杰"
  },
  {
    "id": 112,
    "name": "运维开发",
    "code": "010002",
    "parentId": 2,
    "path": ",0,2,112,",
    "manager": "dk936",
    "orderNo": 2,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:24:44",
    "updateTime": null,
    "userList": [
      {
        "id": 155,
        "userId": "dk936",
        "userName": "丁坤",
        "postName": "运维主管",
        "duty": "",
        "sex": "1",
        "userIdInt": 936,
        "deptId": 2,
        "groupId": 112
      },
      {
        "id": 203,
        "userId": "zsh973",
        "userName": "朱士航",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 973,
        "deptId": 2,
        "groupId": 112
      }
    ],
    "userNums": 2,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "丁坤"
  },
  {
    "id": 175,
    "name": "1组",
    "code": "01",
    "parentId": 112,
    "path": ",0,2,112,175,",
    "manager": "dk936",
    "orderNo": 999,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-11-06 09:54:21",
    "updateTime": null,
    "userList": [
      {
        "id": 26,
        "userId": "hxk852",
        "userName": "黄小康",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 852,
        "deptId": 2,
        "groupId": 175
      },
      {
        "id": 277,
        "userId": "ljm1098",
        "userName": "刘骏铭",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1098,
        "deptId": 2,
        "groupId": 175
      }
    ],
    "userNums": 2,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "丁坤"
  },
  {
    "id": 176,
    "name": "2组",
    "code": "02",
    "parentId": 112,
    "path": ",0,2,112,176,",
    "manager": "zsh973",
    "orderNo": 999,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-11-06 09:54:40",
    "updateTime": null,
    "userList": [
      {
        "id": 722,
        "userId": "zx1348",
        "userName": "张翔",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1348,
        "deptId": 2,
        "groupId": 176
      }
    ],
    "userNums": 1,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "朱士航"
  },
  {
    "id": 114,
    "name": "运维实施",
    "code": "010003",
    "parentId": 2,
    "path": ",0,2,114,",
    "manager": "yzq056",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:25:50",
    "updateTime": null,
    "userList": [
      {
        "id": 21,
        "userId": "yzq056",
        "userName": "杨自谦",
        "postName": "部门副经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 56,
        "deptId": 2,
        "groupId": 114
      },
      {
        "id": 16,
        "userId": "yfq739",
        "userName": "余方青",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 739,
        "deptId": 2,
        "groupId": 114
      },
      {
        "id": 29,
        "userId": "xsb813",
        "userName": "谢尚波",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 813,
        "deptId": 2,
        "groupId": 114
      },
      {
        "id": 128,
        "userId": "fyg897",
        "userName": "范永刚",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 897,
        "deptId": 2,
        "groupId": 114
      },
      {
        "id": 144,
        "userId": "lf926",
        "userName": "李飞",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 926,
        "deptId": 2,
        "groupId": 114
      }
    ],
    "userNums": 5,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "杨自谦"
  },
  {
    "id": 116,
    "name": "1组",
    "code": "010003001",
    "parentId": 114,
    "path": ",0,2,114,116,",
    "manager": "xsb813",
    "orderNo": 1,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:28:14",
    "updateTime": null,
    "userList": [
      {
        "id": 28,
        "userId": "pxj834",
        "userName": "彭锡剑",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 834,
        "deptId": 2,
        "groupId": 116
      },
      {
        "id": 95,
        "userId": "qlm869",
        "userName": "亓利民",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 869,
        "deptId": 2,
        "groupId": 116
      },
      {
        "id": 556,
        "userId": "shh1199",
        "userName": "孙浩浩",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1199,
        "deptId": 2,
        "groupId": 116
      },
      {
        "id": 767,
        "userId": "lzq1377",
        "userName": "李自强",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1377,
        "deptId": 2,
        "groupId": 116
      }
    ],
    "userNums": 4,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "谢尚波"
  },
  {
    "id": 117,
    "name": "2组",
    "code": "010003002",
    "parentId": 114,
    "path": ",0,2,114,117,",
    "manager": "fyg897",
    "orderNo": 2,
    "description": "",
    "createUser": "",
    "updateUser": "",
    "createTime": "2020-07-16 10:28:31",
    "updateTime": null,
    "userList": [
      {
        "id": 646,
        "userId": "jyw1280",
        "userName": "计耀文",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1280,
        "deptId": 2,
        "groupId": 117
      },
      {
        "id": 765,
        "userId": "ygh1375",
        "userName": "杨国恒",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1375,
        "deptId": 2,
        "groupId": 117
      },
      {
        "id": 795,
        "userId": "lyq1404",
        "userName": "李亚卿",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1404,
        "deptId": 2,
        "groupId": 117
      },
      {
        "id": 882,
        "userId": "bsy1491",
        "userName": "鲍森烨",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1491,
        "deptId": 2,
        "groupId": 117
      },
      {
        "id": 890,
        "userId": "chd1500",
        "userName": "陈浩东",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1500,
        "deptId": 2,
        "groupId": 117
      },
      {
        "id": 967,
        "userId": "war1570",
        "userName": "王盎然",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1570,
        "deptId": 2,
        "groupId": 117
      }
    ],
    "userNums": 6,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "范永刚"
  },
  {
    "id": 118,
    "name": "3组",
    "code": "010003003",
    "parentId": 114,
    "path": ",0,2,114,118,",
    "manager": "lf926",
    "orderNo": 3,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2020-07-16 10:29:06",
    "updateTime": null,
    "userList": [
      {
        "id": 638,
        "userId": "hyy1272",
        "userName": "胡意尧",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1272,
        "deptId": 2,
        "groupId": 118
      },
      {
        "id": 844,
        "userId": "lch1454",
        "userName": "李晨辉",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1454,
        "deptId": 2,
        "groupId": 118
      },
      {
        "id": 848,
        "userId": "slc1458",
        "userName": "沈立聪",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1458,
        "deptId": 2,
        "groupId": 118
      },
      {
        "id": 867,
        "userId": "zh1477",
        "userName": "周浩",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1477,
        "deptId": 2,
        "groupId": 118
      },
      {
        "id": 944,
        "userId": "zhs1550",
        "userName": "张瀚森",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1550,
        "deptId": 2,
        "groupId": 118
      }
    ],
    "userNums": 5,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "李飞"
  },
  {
    "id": 199,
    "name": "4组",
    "code": "010003004",
    "parentId": 114,
    "path": ",0,2,114,199,",
    "manager": "yfq739",
    "orderNo": 999,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2022-10-14 03:21:17",
    "updateTime": null,
    "userList": [
      {
        "id": 960,
        "userId": "czf1563",
        "userName": "陈梓帆",
        "postName": "运维",
        "duty": "",
        "sex": "1",
        "userIdInt": 1563,
        "deptId": 2,
        "groupId": 199
      }
    ],
    "userNums": 1,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "余方青"
  },
  {
    "id": 31,
    "name": "质管部",
    "code": "011",
    "parentId": 0,
    "path": ",0,31,",
    "manager": "wtj816",
    "orderNo": 11,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2018-12-29 19:52:48",
    "updateTime": null,
    "userList": [
      {
        "id": 37,
        "userId": "hbx666",
        "userName": "洪彬新",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 666,
        "deptId": 31,
        "groupId": 31
      },
      {
        "id": 82,
        "userId": "wtj816",
        "userName": "伍廷江",
        "postName": "部门经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 816,
        "deptId": 31,
        "groupId": 31
      },
      {
        "id": 559,
        "userId": "py1202",
        "userName": "彭燕",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1202,
        "deptId": 31,
        "groupId": 31
      },
      {
        "id": 892,
        "userId": "cjx1498",
        "userName": "陈佳雪",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1498,
        "deptId": 31,
        "groupId": 31
      },
      {
        "id": 929,
        "userId": "yxr1537",
        "userName": "杨馨茹",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1537,
        "deptId": 31,
        "groupId": 31
      }
    ],
    "userNums": 5,
    "deputyGeneral": "lgq817",
    "deputyGeneralName": "柳刚强",
    "managerName": "伍廷江"
  },
  {
    "id": 193,
    "name": "券商组",
    "code": "011001",
    "parentId": 31,
    "path": ",0,31,193,",
    "manager": "hbx666",
    "orderNo": 1,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-12-03 09:20:33",
    "updateTime": null,
    "userList": [
      {
        "id": 372,
        "userId": "zyl1123",
        "userName": "赵韵林",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1123,
        "deptId": 31,
        "groupId": 193
      },
      {
        "id": 521,
        "userId": "zmy1170",
        "userName": "张梦园",
        "postName": "质管",
        "duty": null,
        "sex": "1",
        "userIdInt": 1170,
        "deptId": 31,
        "groupId": 193
      },
      {
        "id": 868,
        "userId": "wyf1478",
        "userName": "王亚芳",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1478,
        "deptId": 31,
        "groupId": 193
      },
      {
        "id": 932,
        "userId": "hlp1540",
        "userName": "洪丽萍",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1540,
        "deptId": 31,
        "groupId": 193
      }
    ],
    "userNums": 4,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "洪彬新"
  },
  {
    "id": 194,
    "name": "研发组",
    "code": "011002",
    "parentId": 31,
    "path": ",0,31,194,",
    "manager": "py1202",
    "orderNo": 2,
    "description": null,
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-12-03 09:20:54",
    "updateTime": null,
    "userList": [
      {
        "id": 623,
        "userId": "msj1259",
        "userName": "苗帅杰",
        "postName": "质管",
        "duty": null,
        "sex": "1",
        "userIdInt": 1259,
        "deptId": 31,
        "groupId": 194
      },
      {
        "id": 695,
        "userId": "sl1321",
        "userName": "单莉",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1321,
        "deptId": 31,
        "groupId": 194
      },
      {
        "id": 708,
        "userId": "zsd1334",
        "userName": "庄顺达",
        "postName": "质管",
        "duty": null,
        "sex": "1",
        "userIdInt": 1334,
        "deptId": 31,
        "groupId": 194
      },
      {
        "id": 898,
        "userId": "ly1507",
        "userName": "刘燕",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1507,
        "deptId": 31,
        "groupId": 194
      },
      {
        "id": 908,
        "userId": "mxf1516",
        "userName": "马晓锋",
        "postName": "质管",
        "duty": null,
        "sex": "1",
        "userIdInt": 1516,
        "deptId": 31,
        "groupId": 194
      },
      {
        "id": 953,
        "userId": "zyw1556",
        "userName": "朱莹玮",
        "postName": "质管",
        "duty": null,
        "sex": "2",
        "userIdInt": 1556,
        "deptId": 31,
        "groupId": 194
      },
      {
        "id": 970,
        "userId": "hmx1573",
        "userName": "胡铭轩",
        "postName": "质管",
        "duty": null,
        "sex": "1",
        "userIdInt": 1573,
        "deptId": 31,
        "groupId": 194
      }
    ],
    "userNums": 7,
    "deputyGeneral": null,
    "deputyGeneralName": null,
    "managerName": "彭燕"
  },
  {
    "id": 186,
    "name": "系统账号",
    "code": "013",
    "parentId": 0,
    "path": ",0,186,",
    "manager": "lgp090",
    "orderNo": 12,
    "description": "",
    "createUser": null,
    "updateUser": null,
    "createTime": "2021-04-25 09:46:04",
    "updateTime": null,
    "userList": [
      {
        "id": 96,
        "userId": "zz001",
        "userName": "中焯信息",
        "postName": "公司",
        "duty": null,
        "sex": "1",
        "userIdInt": 1,
        "deptId": 186,
        "groupId": 186
      },
      {
        "id": 415,
        "userId": "api001",
        "userName": "API",
        "postName": "技术经理",
        "duty": null,
        "sex": "1",
        "userIdInt": 1,
        "deptId": 186,
        "groupId": 186
      }
    ],
    "userNums": 2,
    "deputyGeneral": "",
    "deputyGeneralName": null,
    "managerName": "李国平"
  },
]


export default  pageList